name: Deploy to Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm install

      - name: Set secret for Firebase Functions
        run: firebase functions:secrets:set OPENAI_API_KEY --project b-scanner-57398 --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Deploy to Firebase
        run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project b-scanner-57398
